import json

SPOTLIGHT = 0 # general interest points
INNOVATION = 1 # describes use of innovative solutions
LEGAL = 2 # tone of legal notice or legal defense/prepping
BUSINESS_FOCUS = 3 # takes a tone that suggests business advancement
DNSMI = 4 # presense of dnsmi references
SECURITY = 5 # describes security measures
CAPABILITY = 6 # describes what user or company can do
EDUCATION = 7 # educational tone
UTILIZATION = 8 # makes known the activity of data utilization
ATTRIBUTING = 9 # describes the activity of profiling
TECHNOLOGY = 10 # directly describes user data/tracking technology
SUGGESTIVE = 11 # general / suspicious or implicative tone

category_d = {
    0:"SPOTLIGHT",
    1:"INNOVATION",
    2:"LEGAL",
    3:"BUSINESS_FOCUS",
    4:"DNSMI",
    5:"SECURITY",
    6:"CAPABILITY",
    7:"EDUCATION",
    8:"UTILIZATION",
    9:"ATTRIBUTING",
    10:"TECHNOLOGY",
    11:"SUGGESTIVE"
}

PRIVACY_POLICY_KEY_PHRASES = {
    "we":SPOTLIGHT,
    "promise":SPOTLIGHT,
    "we will not":CAPABILITY,
    "we only":CAPABILITY,
    "contract":LEGAL,
    "contractual":LEGAL,
    "agreement":LEGAL,
    "you may":CAPABILITY,
    "third parties":BUSINESS_FOCUS,
    "third-party":BUSINESS_FOCUS,
    "third party":BUSINESS_FOCUS,
    "third-party":BUSINESS_FOCUS,
    "we collect certain":CAPABILITY,
    "we collect":CAPABILITY,
    "we may collect":CAPABILITY,
    "we may collect certain":CAPABILITY,
    "we have the right":LEGAL,
    "you can":CAPABILITY,
    "information":SPOTLIGHT,
    "information you":ATTRIBUTING,
    "we create a user profile":ATTRIBUTING,
    "create a user profile":ATTRIBUTING,
    "we profile":ATTRIBUTING,
    "a profile":ATTRIBUTING,
    "we collect information":CAPABILITY,
    "we collect details":CAPABILITY,
    "we send to third":BUSINESS_FOCUS,
    "we sell to third":BUSINESS_FOCUS,
    "we share with third":BUSINESS_FOCUS,
    "we exchange with third":BUSINESS_FOCUS,
    "may send to third":BUSINESS_FOCUS,
    "may lead to third":BUSINESS_FOCUS,
    "may sell to third":BUSINESS_FOCUS,
    "may share with third":BUSINESS_FOCUS,
    "may exchange with third":BUSINESS_FOCUS,
    "to gather data":UTILIZATION,
    "we gather data":CAPABILITY,
    "analyze":INNOVATION,
    "analysis":INNOVATION,
    "analytics":INNOVATION,
    "control options":SECURITY,
    "you control":LEGAL,
    "we control":LEGAL,
    "location information":ATTRIBUTING,
    "location":ATTRIBUTING,
    "usage information":ATTRIBUTING,
    "usage":ATTRIBUTING,
    "usage data":ATTRIBUTING,
    "location data":ATTRIBUTING,
    "may share information":BUSINESS_FOCUS,
    "may share":BUSINESS_FOCUS,
    "we share":BUSINESS_FOCUS,
    "we sell":BUSINESS_FOCUS,
    "how we use":EDUCATION,
    "how":EDUCATION,
    "how you":EDUCATION,
    "explain":EDUCATION,
    "understand":EDUCATION,
    "we sell information":UTILIZATION,
    "how we use your":EDUCATION,
    "use":SPOTLIGHT,
    "for various reasons":SUGGESTIVE,
    "we process personal data":UTILIZATION,
    "we process":UTILIZATION,
    "legal":LEGAL,
    "obligation":LEGAL,
    "authority":LEGAL,
    "comply with":LEGAL,
    "compliant with":LEGAL,
    "law":LEGAL,
    "enforce":LEGAL,
    "govern":LEGAL,
    "sharing of":UTILIZATION,
    "sharing of personal":UTILIZATION,
    "sharing of user":UTILIZATION,
    "fraud":SECURITY,
    "we may disclose":CAPABILITY,
    "to protect":SECURITY,
    "regulators":LEGAL,
    "possibility":SUGGESTIVE,
    "intention":SUGGESTIVE,
    "certain":SUGGESTIVE,
    "certain information":SUGGESTIVE,
    "other":SPOTLIGHT,
    "if":SPOTLIGHT,
    "when":SPOTLIGHT,
    "only":SPOTLIGHT,
    "other data":SUGGESTIVE,
    "other purposes":SUGGESTIVE,
    "other reasons":SUGGESTIVE,
    "other objectives":SUGGESTIVE,
    "business goals":BUSINESS_FOCUS,
    "business purposes":BUSINESS_FOCUS,
    "data controller":UTILIZATION,
    "cookies":TECHNOLOGY,
    "type of cookies":EDUCATION,
    "what are cookies":EDUCATION,
    "how cookies":EDUCATION,
    "why":SPOTLIGHT,
    "automate":INNOVATION,
    "automatic":INNOVATION,
    "AI":INNOVATION,
    "artificial intelligence":INNOVATION,
    "algorithm":INNOVATION,
    "language processing":INNOVATION,
    "rights":LEGAL,
    "consent":LEGAL,
    "right to request":CAPABILITY,
    "dispute":LEGAL,
    "what are":EDUCATION,
    "how are":EDUCATION,
    "learn":EDUCATION,
    "mobile identifiers":TECHNOLOGY,
    "advertising partners":BUSINESS_FOCUS,
    "enterprise":BUSINESS_FOCUS,
    "your choice":CAPABILITY,
    "settings":SECURITY,
    "data collected":UTILIZATION,
    "collected":UTILIZATION,
    "stored":UTILIZATION,
    "retention":UTILIZATION,
    "privacy law":LEGAL,
    "privacy":SPOTLIGHT,
    "do not share my personal information":DNSMI,
    "dnsmi":DNSMI,
    "do not sell my personal information":DNSMI,
    "do not share or sell my personal information":DNSMI,
    "do not share my data":DNSMI,
    "do not sell my data":DNSMI,
    "do not sell or share my data":DNSMI,
    "do not share or sell my data":DNSMI,
    "do not sell or share my personal information":DNSMI,
    "how we collect":EDUCATION,
    "policy":LEGAL,
    "protect personal information":SECURITY,
    "information collected automatically":INNOVATION,
    "collected automatically":INNOVATION,
    "collected by":UTILIZATION,
    "collected with":UTILIZATION,
    "pixel tags":TECHNOLOGY,
    "web beacons":TECHNOLOGY,
    "to detect":SECURITY,
    "malicious":SECURITY,
    "against malicious":SECURITY,
    "against fraud":SECURITY,
    "illegal activity":SECURITY,
    "state laws":LEGAL,
    "international laws":LEGAL,
    "we may share":SUGGESTIVE,
    "with your consent":LEGAL,
    "request access":CAPABILITY,
    "deletion of your personal information":CAPABILITY,
    "deletion of":CAPABILITY,
    "delete":CAPABILITY,
    "remove":CAPABILITY,
    "right to delete":CAPABILITY,
    "right to remove":CAPABILITY,
    "removal":CAPABILITY,
    "erase":CAPABILITY,
    "erase your":CAPABILITY,
    "right to erase":CAPABILITY,
    "explain":EDUCATION,
    "help you":SPOTLIGHT,
    "help us":SPOTLIGHT,
    "your activity":ATTRIBUTING,
    "user behavior":ATTRIBUTING,
    "we don't share information that":CAPABILITY,
    "we don't share information that":CAPABILITY,
    "we use information":UTILIZATION,
    "may use information":UTILIZATION,
    "can access":SPOTLIGHT,
    "can't access":SPOTLIGHT,
    "external processing":UTILIZATION,
    "for legal reasons":SUGGESTIVE,
    "encryption":SECURITY,
    "security":SECURITY,
    "unauthorized":SECURITY,
    "in accordane with":LEGAL,
    "regulators":LEGAL,
    "does not cover":LEGAL,
    "may not cover":SUGGESTIVE,
    "california":LEGAL,
    "other than california":LEGAL,
    "outside of california":LEGAL,
    "right to know":LEGAL,
    "privacy controls":SECURITY,
    "privacy settings":SECURITY,
    "information may be disclosed":LEGAL,
    "information we gather":CAPABILITY,
    "how can i":EDUCATION,
    "how you can":EDUCATION,
    "how to":EDUCATION,
    "owns my data":ATTRIBUTING,
    "owns your data":ATTRIBUTING,
    "how we disclose":EDUCATION,
    "personl records":ATTRIBUTING,
    "purpose for collection":EDUCATION,
    "to improve the service":BUSINESS_FOCUS,
    "to improve":BUSINESS_FOCUS,
    "to optimize":BUSINESS_FOCUS,
    "to increase":BUSINESS_FOCUS,
    "to benefit our":BUSINESS_FOCUS,
    "to enhance our":BUSINESS_FOCUS,
    "to enhance":BUSINESS_FOCUS,
    "to innovate":BUSINESS_FOCUS,
    "technologial innovation":BUSINESS_FOCUS,
    "personal records":ATTRIBUTING,
    "records":ATTRIBUTING,
    "children":LEGAL,
    "kid":LEGAL,
    "child":LEGAL,
    "youth":LEGAL,
    "young":LEGAL,
    "minor":LEGAL,
    "under the age":LEGAL,
    "under-the-age":LEGAL,
    "under age":LEGAL,
    "under-age":LEGAL,
    "session monitoring":TECHNOLOGY,
    "auditing":SECURITY,
    "only when":SUGGESTIVE,
    "only for":SUGGESTIVE,
    "only under":SUGGESTIVE,
    "various purposes":SUGGESTIVE,
    "various objectives":SUGGESTIVE,
    "with your consent":LEGAL,
    "you consented":LEGAL,
    "you consent":LEGAL,
    "you agree":LEGAL,
    "your agreement":LEGAL,
    "you acknowledge":LEGAL,
    "you acknowledged":LEGAL,
    "you signed":LEGAL,
    "you approve":LEGAL,
    "you approved":LEGAL,
    "with your permission":LEGAL,
    "you made it public":LEGAL,
    "you oblige":LEGAL,
    "you obliged":LEGAL,
    "you chose":LEGAL,
    "you choose":LEGAL,
    "when you signed":LEGAL,
    "when you accepted":LEGAL,
    "when you read":LEGAL,
    "when you approved":LEGAL,
    "when you consent":LEGAL,
    "when you acknowledge":LEGAL,
    "if necessary":SUGGESTIVE,
    "for business purpose":SUGGESTIVE
}

d = {}
for phrase in PRIVACY_POLICY_KEY_PHRASES.keys():
    subject = PRIVACY_POLICY_KEY_PHRASES[phrase]
    subject = category_d[subject]
    if subject not in d:
        d[subject] = {}
    
    d[subject][phrase] = 0
        
with open("privacy-policy-clean1-key-phrases.json",'w') as f:
    json.dump(d,f)